import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


public class Dashboard extends javax.swing.JFrame {

    public Dashboard() {
        initComponents();
        loadDashboardData();
        setupNavigation();
    }
    
    private void setupNavigation() {
        GoToUser.addActionListener(e -> {
            new User().setVisible(true);
            this.dispose();
        });
        
        GoToCategory.addActionListener(e -> {
            new Category().setVisible(true);
            this.dispose();
        });
        
        GoToProduct.addActionListener(e -> {
            new Product().setVisible(true);
            this.dispose();
        });
        
        GoToOrder.addActionListener(e -> {
            new Order().setVisible(true);
            this.dispose();
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        UserTotalPanel = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        UserLabelTotalUsers = new javax.swing.JLabel();
        CategoriesTotalPanel = new javax.swing.JPanel();
        CategoriesLabel = new javax.swing.JLabel();
        CategoriesLabelTotalCategories = new javax.swing.JLabel();
        ProductsTotalPanel = new javax.swing.JPanel();
        ProductsLabel = new javax.swing.JLabel();
        ProductsLabelTotalProducts = new javax.swing.JLabel();
        GoToDashboard = new javax.swing.JButton();
        GoToUser = new javax.swing.JButton();
        GoToCategory = new javax.swing.JButton();
        GoToProduct = new javax.swing.JButton();
        GoToOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setName("Dashboard"); // NOI18N

        BackgroundPanel.setBackground(new java.awt.Color(24, 65, 127));
        BackgroundPanel.setMaximumSize(new java.awt.Dimension(1366, 768));
        BackgroundPanel.setMinimumSize(new java.awt.Dimension(1366, 768));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMaximumSize(new java.awt.Dimension(1050, 570));
        MainPanel.setMinimumSize(new java.awt.Dimension(1050, 570));

        HeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        HeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel.setText("Dashboard");

        UserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLabel.setText("Users");

        UserLabelTotalUsers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserLabelTotalUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout UserTotalPanelLayout = new javax.swing.GroupLayout(UserTotalPanel);
        UserTotalPanel.setLayout(UserTotalPanelLayout);
        UserTotalPanelLayout.setHorizontalGroup(
            UserTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(UserLabelTotalUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UserTotalPanelLayout.setVerticalGroup(
            UserTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserTotalPanelLayout.createSequentialGroup()
                .addComponent(UserLabelTotalUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CategoriesLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CategoriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CategoriesLabel.setText("Categories");

        CategoriesLabelTotalCategories.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CategoriesLabelTotalCategories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CategoriesTotalPanelLayout = new javax.swing.GroupLayout(CategoriesTotalPanel);
        CategoriesTotalPanel.setLayout(CategoriesTotalPanelLayout);
        CategoriesTotalPanelLayout.setHorizontalGroup(
            CategoriesTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CategoriesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(CategoriesLabelTotalCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CategoriesTotalPanelLayout.setVerticalGroup(
            CategoriesTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoriesTotalPanelLayout.createSequentialGroup()
                .addComponent(CategoriesLabelTotalCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoriesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ProductsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductsLabel.setText("Products");

        ProductsLabelTotalProducts.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ProductsLabelTotalProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ProductsTotalPanelLayout = new javax.swing.GroupLayout(ProductsTotalPanel);
        ProductsTotalPanel.setLayout(ProductsTotalPanelLayout);
        ProductsTotalPanelLayout.setHorizontalGroup(
            ProductsTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(ProductsLabelTotalProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ProductsTotalPanelLayout.setVerticalGroup(
            ProductsTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductsTotalPanelLayout.createSequentialGroup()
                .addComponent(ProductsLabelTotalProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProductsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(UserTotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CategoriesTotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProductsTotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
            .addComponent(HeaderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel)
                .addGap(120, 120, 120)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserTotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoriesTotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductsTotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        GoToDashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GoToDashboard.setText("Dashboard");
        GoToDashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(51, 153, 255)));

        GoToUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GoToUser.setText("User");
        GoToUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToUserActionPerformed(evt);
            }
        });

        GoToCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GoToCategory.setText("Category");

        GoToProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GoToProduct.setText("Product");

        GoToOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GoToOrder.setText("Order");
        GoToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GoToDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GoToOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GoToCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(GoToProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GoToUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(GoToDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(GoToUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(GoToCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(GoToProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(GoToOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void GoToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoToOrderActionPerformed

    private void GoToUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoToUserActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel CategoriesLabel;
    private javax.swing.JLabel CategoriesLabelTotalCategories;
    private javax.swing.JPanel CategoriesTotalPanel;
    private javax.swing.JButton GoToCategory;
    private javax.swing.JButton GoToDashboard;
    private javax.swing.JButton GoToOrder;
    private javax.swing.JButton GoToProduct;
    private javax.swing.JButton GoToUser;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel ProductsLabel;
    private javax.swing.JLabel ProductsLabelTotalProducts;
    private javax.swing.JPanel ProductsTotalPanel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabelTotalUsers;
    private javax.swing.JPanel UserTotalPanel;
    // End of variables declaration//GEN-END:variables
private void loadDashboardData() {
        Connection conn = DatabaseConnection.getConnection();
        if (conn != null) {
            try {
                // Load user count
                String userQuery = "SELECT COUNT(*) FROM users";
                PreparedStatement userStmt = conn.prepareStatement(userQuery);
                ResultSet userRs = userStmt.executeQuery();
                if (userRs.next()) {
                    UserLabelTotalUsers.setText(String.valueOf(userRs.getInt(1)));
                } else {
                    UserLabelTotalUsers.setText("0");
                }

                // Load category count
                String categoryQuery = "SELECT COUNT(*) FROM categories";
                PreparedStatement categoryStmt = conn.prepareStatement(categoryQuery);
                ResultSet categoryRs = categoryStmt.executeQuery();
                if (categoryRs.next()) {
                    CategoriesLabelTotalCategories.setText(String.valueOf(categoryRs.getInt(1)));
                } else {
                    CategoriesLabelTotalCategories.setText("0");
                }

                // Load product count
                String productQuery = "SELECT COUNT(*) FROM products";
                PreparedStatement productStmt = conn.prepareStatement(productQuery);
                ResultSet productRs = productStmt.executeQuery();
                if (productRs.next()) {
                    ProductsLabelTotalProducts.setText(String.valueOf(productRs.getInt(1)));
                } else {
                    ProductsLabelTotalProducts.setText("0");
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error loading dashboard data: " + e.getMessage());
                // Set default values if database error
                UserLabelTotalUsers.setText("0");
                CategoriesLabelTotalCategories.setText("0");
                ProductsLabelTotalProducts.setText("0");
            } finally {
                DatabaseConnection.closeConnection(conn);
            }
        } else {
            // Set default values if no connection
            UserLabelTotalUsers.setText("0");
            CategoriesLabelTotalCategories.setText("0");
            ProductsLabelTotalProducts.setText("0");
        }
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }
}